//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string FilePath { get; set; }
        public string FileExtension { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<int> UploadedBy { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Users Users { get; set; }
    }
}
