//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemSettings
    {
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> MaxUploadSizeMB { get; set; }
        public Nullable<bool> IsMaintenanceMode { get; set; }
        public Nullable<bool> AllowRegistration { get; set; }
        public Nullable<bool> EnableAuditLogs { get; set; }
    }
}
